'use strict';

// querySelector is method avaiable on the document
// within the parentheses we add the selector which is the class name (or the ID)

// console.log(document.querySelector('.message').textContent);

// the DOM in Web Dev is the 'Document Object Model' 
// structured representation of HTML documents. It allows javascript to access HTML elements and styles to manipulate them.
// so with DOM manipulation, you can change text, html attributes, and even CSS styles from Javascript.

//So the DOM is like a connection point between HTML and Javascript 
// The DOM is automatically created by the browser as soon as the HTML page loads. 
// its sort of done as a tree strucuter, generated by browser on HTML load. 
// at the top of that tree structure is the Document Object (DOM) and the Document Object is what we have access to in JavaScript
// So the Document Object is the entry point into the DOM. Thats why we write document.querySelector...cause we are calling to the DOM by the document object

// Contrary to popular Assumption, the DOM and all its methods & properties for manipulation, are not part of JavaScript

// Thats right, the DOM is not JavaScript 

// What the DOM acctually is is part of WEB APIS...that all browsers use...thats where all the DOM methods and Properties are from.
// API stands for Application Programming Interface

// The API's are bascilly Web Libraries that are written in JavaScript, and available for us to us in Javascript
// This all occurs behind the scenes so we don't need to import or do anything. 
// Timers and Fetch are also from Web APIS

// Now lets get back to actual work. 


console.log(document.querySelector('.message').textContent);

//  so the above was to get content, but we can also change content 

document.querySelector('.message').textContent = 'Correct Number!';

// so now when we console.log it again, its differnet.

console.log(document.querySelector('.message').textContent);

// THIS is all DOM Manipulation

// so now lets select the elements with the class number and the class score 

document.querySelector('.number').textContent = 13;
document.querySelector('.score').textContent = 10;

console.log(document.querySelector('.guess').value);
// guess has no value currently so it might trigger and error, or console.log nothing
// but we can create content

document.querySelector('.guess').value = 23;

console.log(document.querySelector('.guess').value);