'use strict';

// querySelector is method avaiable on the document
// within the parentheses we add the selector which is the class name (or the ID)

// console.log(document.querySelector('.message').textContent);

// the DOM in Web Dev is the 'Document Object Model' 
// structured representation of HTML documents. It allows javascript to access HTML elements and styles to manipulate them.
// so with DOM manipulation, you can change text, html attributes, and even CSS styles from Javascript.

//So the DOM is like a connection point between HTML and Javascript 
// The DOM is automatically created by the browser as soon as the HTML page loads. 
// its sort of done as a tree strucuter, generated by browser on HTML load. 
// at the top of that tree structure is the Document Object (DOM) and the Document Object is what we have access to in JavaScript
// So the Document Object is the entry point into the DOM. Thats why we write document.querySelector...cause we are calling to the DOM by the document object

// Contrary to popular Assumption, the DOM and all its methods & properties for manipulation, are not part of JavaScript

// Thats right, the DOM is not JavaScript 

// What the DOM acctually is is part of WEB APIS...that all browsers use...thats where all the DOM methods and Properties are from.
// API stands for Application Programming Interface

// The API's are bascilly Web Libraries that are written in JavaScript, and available for us to us in Javascript
// This all occurs behind the scenes so we don't need to import or do anything. 
// Timers and Fetch are also from Web APIS

// Now lets get back to actual work. 


// console.log(document.querySelector('.message').textContent);

//  so the above was to get content, but we can also change content 

// document.querySelector('.message').textContent = 'Correct Number!';

// so now when we console.log it again, its differnet.

// console.log(document.querySelector('.message').textContent);

// THIS is all DOM Manipulation

// so now lets select the elements with the class number and the class score 

// document.querySelector('.number').textContent = 13;
// document.querySelector('.score').textContent = 10;

// console.log(document.querySelector('.guess').value);
// guess has no value currently so it might trigger and error,
// or console.log nothing
// but we can create content

// document.querySelector('.guess').value = 23;

// console.log(document.querySelector('.guess').value);

// now to get the code to react to something in the DOM, we use an Event Listener
// An event is something that happens on the page, like a mouse click or hover 

// An event listener allows us to wait until something happens.

// with the event listener, the target we want to listne to is the check button 

// so we select the element using query selector, and we set the addEventListener to trigger at a click, and then we set a function expression telling it what to do on the click

const secretNumber = Math.trunc(Math.random() * 20) + 1;
document.querySelector('.number').textContent = secretNumber;

let score = 20;

document.querySelector('.check').addEventListener('click', function () {
  //console.log(document.querySelector('.guess').value);
  const guess = Number(document.querySelector('.guess').value);
  console.log(guess, typeof guess);
  // for the game logic, the first scenario is always to assume there is no input
  //if there is no guess
  if (!guess) {
    document.querySelector('.message').textContent = 'No number!';

  } else if (guess === secretNumber) {
    document.querySelector('.message').textContent = 'Correct Number!';
    score++
    document.querySelector('.score').textContent = score;
  } else if (guess > secretNumber) {
    if (score > 1) {
      document.querySelector('.message').textContent = 'Too High';
      score--
      document.querySelector('.score').textContent = score;
    } else {
      document.querySelector('.message').textContent = 'You Lost the game';
      document.querySelector('.score').textContent = 0;
    }
  } else if (guess < secretNumber) {
    if (score > 1) {
      document.querySelector('.message').textContent = 'Too Low';
      score--
      document.querySelector('.score').textContent = score;
    } else {
      document.querySelector('.message').textContent = 'You Lost the game';
      document.querySelector('.score').textContent = 0;
    }
   
  }
})

// one thing to note, the function expression in this instance does not need to be called, since the addEventListener will by default call it when its triggers

// Another thing to note, typically when you get any data from the user interface, it will almost always return a string. So for number inputs...those too get stored as strings. Since for this app we need the number to read and function as a number, we need to convert the string to a number.
// So in this case we add the Number operator  

// now the secret number (that is being guessed on) would only get called once at the load of the page, and should exist outside of the main function. If you define the secret number on the event listner, you would get a new secret number every click 

// now for the score, the best thing is to create it as a variable and decrease or increase it as needed. 